name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r gw_spaceheat/requirements/base.txt
          pip install -r gw_spaceheat/requirements/test.txt
      - name: copy test_settings
        uses: canastro/copy-file-action@master
        with:
          source: "test/test_settings.py"
          target: "gw_spaceheat/settings.py"
      - name: copy test_dotenv
        uses: canastro/copy-file-action@master
        with:
          source: "test/test_dotenv"
          target: ".env"
      - name: Run tests with pytest
        run: pytest
